#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path


# These descriptions are retained for reference by design tooling. Artifact
# directories are now created lazily by initialize_design_artifacts.py.
README_TEXT = {
    "context/relative/README.md": """# Relative Context

This directory contains information specific to this initiative. Add only
context needed to understand and design the change.

Examples:

- Current-state architecture
- Impacted services and repositories
- Existing APIs and events
- Relevant ADRs
- Runtime or deployment evidence
- Initiative-specific constraints
- Business or regional details not covered by shared context

The requirement remains at the initiative root:

```text
../requirement.md
```

The AI context builder will combine this directory with shared context and
guardrails before invoking an agent.
""",
    "hld/README.md": """# High-Level Design

Create this content only after the requirement is approved and the relevant
context has been assembled.

Expected proposal content:

- Solution concept
- Constraints and guardrails
- Non-functional requirements
- Multiple architecture options
- Trade-off analysis
- Recommended option
- Delivery plan
- Cloud or deployment view
- Mermaid context, C4 Level 1, C4 Level 2, deployment, and sequence diagrams
  where applicable; include an ERD when meaningful data ownership or
  persistence is part of the HLD
- Risks and mitigations
- Migration and rollback
- Proposed ADRs
- Open questions

Architecture approval is recorded only after human Solution Architect or ARB
review. An HLD approval unlocks engineering design; the AI cannot grant it.
""",
    "lld/README.md": """# Engineering Design

Create this content only after the HLD approval gate has passed.

Expected content may include:

- Low-level design
- API and event contracts
- Data and migration changes
- Sequence and component diagrams
- TDD and test strategy
- Observability strategy
- Implementation plan
""",
    "feedback/README.md": """# Feedback

Store structured human feedback here. Feedback should identify the artifact,
sections affected, reviewer, decision, and requested rerun scope.
""",
    "approvals/README.md": """# Approvals

Human approvals are recorded here as Markdown review records and in GitHub PR
history. An approval applies to the exact artifact version and content hash.

Agents and automation may prepare a review request, but may not approve it.
""",
    "evidence/README.md": """# Evidence

Generated context snapshots, agent requests and responses, validation output,
source hashes, and deployment evidence belong here. Evidence is generated by
the workflow and should not normally be authored manually.
""",
}

TEMPLATE_FILES = {
    "initiative.md": "initiative.md",
    "initiative.yaml": "initiative.yaml",
    "approvals.yaml": "approvals.yaml",
    "traceability.yaml": "traceability.yaml",
    "context-manifest.yaml": "context-manifest.yaml",
}


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def replace_first(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        fail(f"Could not update {label}")
    return updated


def update_workflow_state(initiative_yaml: Path, expected: str, new_value: str) -> bool:
    text = initiative_yaml.read_text()
    pattern = rf"^(\s*state:\s*){re.escape(expected)}$"
    updated, count = re.subn(pattern, rf"\1{new_value}", text, count=1, flags=re.MULTILINE)
    if count == 0:
        return False
    initiative_yaml.write_text(updated)
    return True


def metadata(initiative_yaml: Path) -> dict[str, str]:
    text = initiative_yaml.read_text()
    values = {}
    for key in ("title", "owner"):
        match = re.search(rf'^\s+{key}:\s*"([^"]*)"\s*$', text, flags=re.MULTILINE)
        if match:
            values[key] = match.group(1)
    initiative_match = re.search(r'^\s+id:\s*"([^"]+)"\s*$', text, flags=re.MULTILINE)
    if initiative_match:
        values["id"] = initiative_match.group(1)
    return values


def requirement_metadata(requirement: Path) -> dict[str, str]:
    text = requirement.read_text()
    values = {}
    patterns = {
        "title": r'^\s+title:\s*"([^"]*)"\s*$',
        "owner": r'^\s+owner:\s*"([^"]*)"\s*$',
        "provider": r'^\s+provider:\s*"([^"]*)"\s*$',
        "work_item_id": r'^\s+work_item_id:\s*"([^"]*)"\s*$',
        "risk_tier": r'^\s+risk_tier:\s*"([^"]*)"\s*$',
        "data_classification": r'^\s+data_classification:\s*"([^"]*)"\s*$',
    }
    for key, pattern in patterns.items():
        match = re.search(pattern, text, flags=re.MULTILINE)
        if match:
            values[key] = match.group(1)
    initiative_match = re.search(r'^\s+initiative:\s*"([^"]+)"\s*$', text, flags=re.MULTILINE)
    if initiative_match:
        values["id"] = initiative_match.group(1)
    return values


def render_template(source: Path, target: Path, values: dict[str, str]) -> None:
    text = source.read_text()
    replacements = {
        "{{ initiative.id }}": values.get("id", target.parent.parent.parent.name),
        "{{ initiative.title }}": values.get("title", "Untitled initiative"),
        "{{ initiative.owner }}": values.get("owner", "team.example"),
        "{{ initiative.domains }}": "[]",
        "{{ initiative.repositories }}": "[]",
        "{{ source.provider }}": values.get("provider", "github"),
        "{{ source.work_item_id }}": values.get("work_item_id", values.get("id", "")),
        "{{ policy.risk_tier }}": values.get("risk_tier", "medium"),
        "{{ policy.data_classification }}": values.get("data_classification", "internal"),
        "{{ roles.solution_architect }}": "team.solution-architecture",
        "{{ roles.senior_engineer }}": "team.engineering",
    }
    for placeholder, value in replacements.items():
        text = text.replace(placeholder, value)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)


def main() -> int:
    if len(sys.argv) != 2:
        fail("Usage: expand_initiative.py <initiative-dir>")

    initiative_dir = Path(sys.argv[1]).resolve()
    if not initiative_dir.is_dir():
        fail(f"Initiative directory not found: {initiative_dir}")

    created_any = False
    initiative_yaml = initiative_dir / "initiative.yaml"
    requirement_md = initiative_dir / "requirement.md"
    template_root = initiative_dir.parent.parent / "templates" / "initiative"
    values = metadata(initiative_yaml) if initiative_yaml.exists() else {}
    if not values and requirement_md.exists():
        values = requirement_metadata(requirement_md)
    for relative, template_relative in TEMPLATE_FILES.items():
        path = initiative_dir / relative
        if path.exists():
            continue
        source = template_root / template_relative
        if not source.exists():
            fail(f"Initiative template not found: {source}")
        render_template(source, path, values)
        created_any = True

    if initiative_yaml.exists() and update_workflow_state(initiative_yaml, "intake", "scaffolded"):
        created_any = True

    if created_any:
        print(f"Expanded scaffold for {initiative_dir.name}")
    else:
        print(f"No scaffold changes needed for {initiative_dir.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
