#!/usr/bin/env python3
"""Check or safely append missing context-index entries."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_context_pack import sources  # noqa: E402
from context_selection import parse_index, words  # noqa: E402


STOPWORDS = {"context", "consistent", "guardrails", "architecture", "platform", "technology", "business", "product", "security", "principles", "and"}


def heading_titles(text: str) -> list[str]:
    return [match.group(1).strip() for match in re.finditer(r"^#{2,3}\s+(.+?)\s*$", text, re.MULTILINE)]


def suggestion(repo_root: Path, entry: dict[str, str]) -> str:
    source = entry.get("source", "")
    path = repo_root / source
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    title_match = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else entry["id"].replace("-", " ").title()
    terms = sorted(words(entry["id"].replace("-", " ") + " " + title) - STOPWORDS)[:12]
    headings = heading_titles(text)
    selected = [heading for heading in headings if re.search(r"hld|requirement|implication|decision|guardrail|boundary|design", heading, re.I)][:4]
    if not selected:
        selected = headings[:2] or ["all"]
    summary = f"Review and describe {title.lower()} for HLD context selection."
    quote = lambda value: '"' + value.replace('"', "'") + '"'
    return "\n".join([
        f"    - id: {entry['id']}",
        f"      summary: {quote(summary)}",
        f"      keywords: [{', '.join(terms)}]",
        f"      selected_sections: [{', '.join(quote(item) for item in selected)}]",
        "      priority: review-required",
        "      applies_to: [review-required]",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--update", action="store_true", help="Append stubs for missing entries; never delete or overwrite entries")
    args = parser.parse_args()
    repo_root = args.root.resolve()
    registry = repo_root / "ai-sdlc" / "config" / "context-sources.yaml"
    index_path = repo_root / "ai-sdlc" / "config" / "context-index.yaml"
    source_entries = sources(registry)
    _, _, index_entries = parse_index(index_path)
    missing = [entry for entry in source_entries if entry["id"] not in index_entries]
    if not missing:
        print(f"Context catalog is up to date: {len(source_entries)} sources indexed.")
        return 0

    local = [entry for entry in missing if (repo_root / entry.get("source", "")).is_file()]
    provider = [entry for entry in missing if entry not in local]
    print(f"Missing context catalog entries: {len(missing)}")
    if local:
        print("Local sources: " + ", ".join(entry["id"] for entry in local))
    if provider:
        print("Provider-backed sources: " + ", ".join(entry["id"] for entry in provider))
    if not args.update:
        print("Run with --update to append review-required stubs.", file=sys.stderr)
        return 1

    text = index_path.read_text(encoding="utf-8").rstrip() + "\n"
    text += "\n# Entries below were generated by sync_context_catalog.py and require human refinement.\n"
    text += "\n\n".join(suggestion(repo_root, entry) for entry in missing) + "\n"
    index_path.write_text(text, encoding="utf-8")
    print(f"Appended {len(missing)} review-required catalog stubs to {index_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
